### Get All Users
GET http://localhost:3000/auth

### Add a new User
POST http://localhost:3000/auth

### Get user by ID
GET http://localhost:3000/auth/100

### Update a User by ID
PUT http://localhost:3000/auth/100

### Delete User by ID
DELETE http://localhost:3000/auth/100